export const RouterEndpoints = {
    index: '/',
    home: '',
    about: 'about',
    users: 'users',
    companies: 'companies',
    sign_in: 'sign_in',
    sign_up: 'sign_up',
    owner_profile: 'profile',
    account: 'account',
    dashboard: 'dashboard',
    logout: 'logout',
    activate: 'auth/users/activation',
    notFound: '*',
};
